basePath: /
definitions:
  dto.CreateUserInput:
    properties:
      discordID:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    required:
    - email
    - nickname
    - password
    type: object
  dto.ErrorResponse:
    properties:
      error:
        example: usuário não encontrado
        type: string
    type: object
  dto.UpdateUser:
    properties:
      discordID:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    type: object
  dto.UserResponse:
    properties:
      discordID:
        type: string
      email:
        type: string
      eventCount:
        type: integer
      guideCount:
        type: integer
      isModerator:
        type: boolean
      isVeteran:
        type: boolean
      nickname:
        type: string
      registrationDate:
        type: string
      userID:
        type: integer
    type: object
  models.Event:
    properties:
      bannerURL:
        type: string
      day:
        type: string
      description:
        type: string
      eventID:
        type: integer
      lastEvents:
        description: Has many LastEvents
        items:
          $ref: '#/definitions/models.LastEvent'
        type: array
      title:
        type: string
      userID:
        description: Foreign Key (Belongs to User)
        type: integer
    type: object
  models.Guide:
    properties:
      bannerURL:
        type: string
      characterID:
        type: integer
      creationDate:
        type: string
      description:
        type: string
      dislikes:
        type: integer
      guideID:
        type: integer
      likes:
        type: integer
      link:
        type: string
      title:
        type: string
      type:
        type: string
      userID:
        description: Foreign Keys (Belongs to User and Character)
        type: integer
    type: object
  models.LastEvent:
    properties:
      eventID:
        description: Foreign Key (Belongs to Event)
        type: integer
      lastEventID:
        type: integer
      title:
        type: string
    type: object
  models.User:
    properties:
      discordID:
        type: string
      email:
        type: string
      eventCount:
        type: integer
      events:
        description: Has many Events and Guides
        items:
          $ref: '#/definitions/models.Event'
        type: array
      guideCount:
        type: integer
      guides:
        items:
          $ref: '#/definitions/models.Guide'
        type: array
      isModerator:
        type: boolean
      isVeteran:
        type: boolean
      nickname:
        type: string
      password:
        type: string
      registrationDate:
        type: string
      userID:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de guias, eventos e personagens.
  title: Feel The Night API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Cria um usuário com os dados informados no body.
      parameters:
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Criar um novo usuário
      tags:
      - User
  /users/{id}:
    delete:
      parameters:
      - description: ID do usuário
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Deletar usuário por ID
      tags:
      - User
    get:
      parameters:
      - description: ID do usuário
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Buscar usuário por ID
      tags:
      - User
    patch:
      consumes:
      - application/json
      parameters:
      - description: ID do usuário
        in: path
        minimum: 1
        name: id
        required: true
        type: integer
      - description: Dados para atualização
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorResponse'
      summary: Atualizar dados do usuário
      tags:
      - User
swagger: "2.0"
