basePath: /
definitions:
  dto.CreateUserInput:
    properties:
      discordID:
        type: string
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
    required:
    - email
    - nickname
    - password
    type: object
  models.Character:
    properties:
      character_id:
        type: integer
      description:
        type: string
      guides:
        items:
          $ref: '#/definitions/models.Guide'
        type: array
      image_url:
        type: string
      name:
        type: string
      type:
        type: string
    type: object
  models.Event:
    properties:
      banner_url:
        type: string
      day:
        type: string
      description:
        type: string
      event_id:
        type: integer
      title:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.Guide:
    properties:
      banner_url:
        type: string
      character:
        $ref: '#/definitions/models.Character'
      character_id:
        type: integer
      creation_date:
        type: string
      description:
        type: string
      dislikes:
        type: integer
      guide_id:
        type: integer
      likes:
        type: integer
      link:
        type: string
      title:
        type: string
      type:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      discord_id:
        type: string
      email:
        type: string
      event_count:
        type: integer
      events:
        items:
          $ref: '#/definitions/models.Event'
        type: array
      guide_count:
        type: integer
      guides:
        items:
          $ref: '#/definitions/models.Guide'
        type: array
      is_moderator:
        type: boolean
      is_veteran:
        type: boolean
      nickname:
        type: string
      password:
        type: string
      registration_date:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para gerenciamento de guias, eventos e personagens.
  title: Feel The Night API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Cria um usuário com os dados informados no body.
      parameters:
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Criar um novo usuário
      tags:
      - User
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Retorna os dados de um usuário pelo ID
      parameters:
      - description: Dados do usuário
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Buscar usuário por ID
      tags:
      - User
swagger: "2.0"
